version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - webapp:webapp
